language: node_js
node_js:
  - node
install:
  - echo Not installing dependencies
script:
  - echo Not running tests
deploy:
  provider: npm
  email: $NPM_REG_EMAIL
  api_key: $NPM_REG_TOKEN
  skip_cleanup: true
  on:
    tags: true
    branch: master
